name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Setup project structure
        run: |
          # Create necessary directories if they don't exist
          mkdir -p exports
          mkdir -p uploads
          mkdir -p logs
          
          # Ensure proper permissions
          chmod -R 755 scripts
          chmod -R 755 exports
          chmod -R 755 uploads
          chmod -R 755 logs
          
          # Create .nojekyll file to prevent Jekyll processing
          touch .nojekyll
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
          enable_jekyll: false